In [3]:
import numpy as np
import pandas as pd

df = pd.read_csv('Titanic-Dataset.csv')
# print(df)
# print(df.to_string())
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [5]:
df.tail()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [6]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

Data cleaning

In [7]:
df["Age"]

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ...
886    27.0
887    19.0
888     NaN
889    26.0
890    32.0
Name: Age, Length: 891, dtype: float64

In [8]:
df1 = df
df1

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

Handling Missing Values

In [9]:
df1["Age"].fillna(df1["Age"].mean(), inplace=True)
# df.fillna({"Age": df["Age"].median()}, inplace = True)

In [10]:
df1["Age"]

0      22.000000
1      38.000000
2      26.000000
3      35.000000
4      35.000000
         ...
886    27.000000
887    19.000000
888    29.699118
889    26.000000
890    32.000000
Name: Age, Length: 891, dtype: float64

In [11]:
df1

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.000000,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.000000,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.000000,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.000000,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.000000,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.000000,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.000000,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,29.699118,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.000000,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.000000,0,0,370376,7.7500,NaN,Q

Dropping columns

In [12]:
df1.drop(columns = ['Cabin','Ticket'],axis = 1, inplace = True)

In [13]:
df1

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.000000,1,0,7.2500,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.000000,1,0,71.2833,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.000000,0,0,7.9250,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.000000,1,0,53.1000,S
4,5,0,3,"Allen, Mr. William Henry",male,35.000000,0,0,8.0500,S
...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.000000,0,0,13.0000,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.000000,0,0,30.0000,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,29.699118,1,2,23.4500,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.000000,0,0,30.0000,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.000000,0,0,7.7500,Q

Mapping Categories: if there are feu categoring chanfing it into numbers

In [14]:
df1["Sex"] = df1["Sex"].map({"male": 0, "female":1})
df1

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",0,22.000000,1,0,7.2500,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,38.000000,1,0,71.2833,C
2,3,1,3,"Heikkinen, Miss. Laina",1,26.000000,0,0,7.9250,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,35.000000,1,0,53.1000,S
4,5,0,3,"Allen, Mr. William Henry",0,35.000000,0,0,8.0500,S
...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",0,27.000000,0,0,13.0000,S
887,888,1,1,"Graham, Miss. Margaret Edith",1,19.000000,0,0,30.0000,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",1,29.699118,1,2,23.4500,S
889,890,1,1,"Behr, Mr. Karl Howell",0,26.000000,0,0,30.0000,C
890,891,0,3,"Dooley, Mr. Patrick",0,32.000000,0,0,7.7500,Q

In [15]:
df1 = df1.rename(columns = {"Sex": "Gender"})
df1

,PassengerId,Survived,Pclass,Name,Gender,Age,SibSp,Parch,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",0,22.000000,1,0,7.2500,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,38.000000,1,0,71.2833,C
2,3,1,3,"Heikkinen, Miss. Laina",1,26.000000,0,0,7.9250,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,35.000000,1,0,53.1000,S
4,5,0,3,"Allen, Mr. William Henry",0,35.000000,0,0,8.0500,S
...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",0,27.000000,0,0,13.0000,S
887,888,1,1,"Graham, Miss. Margaret Edith",1,19.000000,0,0,30.0000,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",1,29.699118,1,2,23.4500,S
889,890,1,1,"Behr, Mr. Karl Howell",0,26.000000,0,0,30.0000,C
890,891,0,3,"Dooley, Mr. Patrick",0,32.000000,0,0,7.7500,Q

Exploratory Data analysis(EDA)

In [16]:
df1[(df1['Gender'] == 1) & (df['Pclass'] == 1)]
df1

,PassengerId,Survived,Pclass,Name,Gender,Age,SibSp,Parch,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",0,22.000000,1,0,7.2500,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,38.000000,1,0,71.2833,C
2,3,1,3,"Heikkinen, Miss. Laina",1,26.000000,0,0,7.9250,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,35.000000,1,0,53.1000,S
4,5,0,3,"Allen, Mr. William Henry",0,35.000000,0,0,8.0500,S
...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",0,27.000000,0,0,13.0000,S
887,888,1,1,"Graham, Miss. Margaret Edith",1,19.000000,0,0,30.0000,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",1,29.699118,1,2,23.4500,S
889,890,1,1,"Behr, Mr. Karl Howell",0,26.000000,0,0,30.0000,C
890,891,0,3,"Dooley, Mr. Patrick",0,32.000000,0,0,7.7500,Q

In [17]:
df1.groupby("Pclass")["Survived"].mean()

Pclass
1    0.629630
2    0.472826
3    0.242363
Name: Survived, dtype: float64

In [18]:
(df1.sort_values('Age', ascending=False))

,PassengerId,Survived,Pclass,Name,Gender,Age,SibSp,Parch,Fare,Embarked
630,631,1,1,"Barkworth, Mr. Algernon Henry Wilson",0,80.00,0,0,30.0000,S
851,852,0,3,"Svensson, Mr. Johan",0,74.00,0,0,7.7750,S
96,97,0,1,"Goldschmidt, Mr. George B",0,71.00,0,0,34.6542,C
493,494,0,1,"Artagaveytia, Mr. Ramon",0,71.00,0,0,49.5042,C
116,117,0,3,"Connors, Mr. Patrick",0,70.50,0,0,7.7500,Q
...,...,...,...,...,...,...,...,...,...,...
831,832,1,2,"Richards, Master. George Sibley",0,0.83,1,1,18.7500,S
469,470,1,3,"Baclini, Miss. Helene Barbara",1,0.75,2,1,19.2583,C
644,645,1,3,"Baclini, Miss. Eugenie",1,0.75,2,1,19.2583,C
755,756,1,2,"Hamalainen, Master. Viljo",0,0.67,1,1,14.5000,S
803,804,1,3,"Thomas, Master. Assad Alexander",0,0.42,0,1,8.5167,C

In [19]:
(df1.loc[df1['Age'] > 60, ['Name', 'Age', 'Fare']].head(10))

                                  Name   Age      Fare
33               Wheadon, Mr. Edward H  66.0   10.5000
54      Ostby, Mr. Engelhart Cornelius  65.0   61.9792
96           Goldschmidt, Mr. George B  71.0   34.6542
116               Connors, Mr. Patrick  70.5    7.7500
170          Van der hoef, Mr. Wyckoff  61.0   33.5000
252          Stead, Mr. William Thomas  62.0   26.5500
275  Andrews, Miss. Kornelia Theodosia  63.0   77.9583
280                   Duane, Mr. Frank  65.0    7.7500
326          Nysveen, Mr. Johan Hansen  61.0    6.2375
438                  Fortune, Mr. Mark  64.0  263.0000

In [20]:
top_payers = df1.sort_values('Fare', ascending=False)

In [21]:
top_payers

,PassengerId,Survived,Pclass,Name,Gender,Age,SibSp,Parch,Fare,Embarked
258,259,1,1,"Ward, Miss. Anna",1,35.000000,0,0,512.3292,C
737,738,1,1,"Lesurer, Mr. Gustave J",0,35.000000,0,0,512.3292,C
679,680,1,1,"Cardeza, Mr. Thomas Drake Martinez",0,36.000000,0,1,512.3292,C
88,89,1,1,"Fortune, Miss. Mabel Helen",1,23.000000,3,2,263.0000,S
27,28,0,1,"Fortune, Mr. Charles Alexander",0,19.000000,3,2,263.0000,S
...,...,...,...,...,...,...,...,...,...,...
633,634,0,1,"Parr, Mr. William Henry Marsh",0,29.699118,0,0,0.0000,S
413,414,0,2,"Cunningham, Mr. Alfred Fleming",0,29.699118,0,0,0.0000,S
822,823,0,1,"Reuchlin, Jonkheer. John George",0,38.000000,0,0,0.0000,S
732,733,0,2,"Knight, Mr. Robert J",0,29.699118,0,0,0.0000,S
674,675,0,2,"Watson, Mr. Ennis Hastings",0,29.699118,0,0,0.0000,S

In [22]:
df1['Family_Size'] = df1['SibSp'] + df1['Parch']  +1

In [23]:
df1

,PassengerId,Survived,Pclass,Name,Gender,Age,SibSp,Parch,Fare,Embarked,Family_Size
0,1,0,3,"Braund, Mr. Owen Harris",0,22.000000,1,0,7.2500,S,2
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,38.000000,1,0,71.2833,C,2
2,3,1,3,"Heikkinen, Miss. Laina",1,26.000000,0,0,7.9250,S,1
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,35.000000,1,0,53.1000,S,2
4,5,0,3,"Allen, Mr. William Henry",0,35.000000,0,0,8.0500,S,1
...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",0,27.000000,0,0,13.0000,S,1
887,888,1,1,"Graham, Miss. Margaret Edith",1,19.000000,0,0,30.0000,S,1
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",1,29.699118,1,2,23.4500,S,4
889,890,1,1,"Behr, Mr. Karl Howell",0,26.000000,0,0,30.0000,C,1
890,891,0,3,"Dooley, Mr. Patrick",0,32.000000,0,0,7.7500,Q,1

In [24]:
df1['Title'] =  df1['Name'].str.split(',').str[1].str.split('.').str[0].str.strip()

In [25]:
df1

,PassengerId,Survived,Pclass,Name,Gender,Age,SibSp,Parch,Fare,Embarked,Family_Size,Title
0,1,0,3,"Braund, Mr. Owen Harris",0,22.000000,1,0,7.2500,S,2,Mr
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,38.000000,1,0,71.2833,C,2,Mrs
2,3,1,3,"Heikkinen, Miss. Laina",1,26.000000,0,0,7.9250,S,1,Miss
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,35.000000,1,0,53.1000,S,2,Mrs
4,5,0,3,"Allen, Mr. William Henry",0,35.000000,0,0,8.0500,S,1,Mr
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",0,27.000000,0,0,13.0000,S,1,Rev
887,888,1,1,"Graham, Miss. Margaret Edith",1,19.000000,0,0,30.0000,S,1,Miss
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",1,29.699118,1,2,23.4500,S,4,Miss
889,890,1,1,"Behr, Mr. Karl Howell",0,26.000000,0,0,30.0000,C,1,Mr
890,891,0,3,"Dooley, Mr. Patrick",0,32.000000,0,0,7.7500,Q,1,Mr

In [27]:
bins = [0, 12, 18, 60, 100]
labels = ['Child', 'Teenager', 'Adult', 'Senior'] 
df1['Age_Group'] = pd.cut(df['Age'], bins=bins, labels=labels)

In [28]:
df1

,PassengerId,Survived,Pclass,Name,Gender,Age,SibSp,Parch,Fare,Embarked,Family_Size,Title,Age_Group
0,1,0,3,"Braund, Mr. Owen Harris",0,22.000000,1,0,7.2500,S,2,Mr,Adult
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,38.000000,1,0,71.2833,C,2,Mrs,Adult
2,3,1,3,"Heikkinen, Miss. Laina",1,26.000000,0,0,7.9250,S,1,Miss,Adult
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,35.000000,1,0,53.1000,S,2,Mrs,Adult
4,5,0,3,"Allen, Mr. William Henry",0,35.000000,0,0,8.0500,S,1,Mr,Adult
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",0,27.000000,0,0,13.0000,S,1,Rev,Adult
887,888,1,1,"Graham, Miss. Margaret Edith",1,19.000000,0,0,30.0000,S,1,Miss,Adult
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",1,29.699118,1,2,23.4500,S,4,Miss,Adult
889,890,1,1,"Behr, Mr. Karl Howell",0,26.000000,0,0,30.0000,C,1,Mr,Adult
890,891,0,3,"Dooley, Mr. Patrick",0,32.000000,0,0,7.7500,Q,1,Mr,Adult